// Generated by CoffeeScript 1.12.7
var add, addLines, calcWait, changeFirstExplain, output, play, sim, start, timeFormat;

window.BORDER_WIDTH = 600;

window.RANK_COUNT = 5;

window.OUTPUT_FREQUENCY = 100;

window.timer = false;

window.bests = [];

window.worsts = [];

window.average = 0;

window.count = 0;

$().ready(function() {
  $('input[type="checkbox"]').radiocheck();
  $('#start').on('click', start);
  $('#first').on('change', changeFirstExplain);
  return changeFirstExplain();
});

changeFirstExplain = function() {
  if ($('#first').prop('checked')) {
    return $('#first_explain').html('バスが来る時間帯の最初にバス停に到着したとする');
  } else {
    return $('#first_explain').html('ランダムな時間にバス停に到着したとする（もうバスが来なければ、バスが来る時間帯の終わりまで待つとする）');
  }
};

start = function() {
  if (window.timer === false) {
    window.BUS_COUNT = Number($('#bus_count').val());
    window.TIME_MINUTES = 60 * Number($('#hour').val());
    window.isFirst = $('#first').prop('checked');
    window.bests = [];
    window.worsts = [];
    window.average = 0;
    window.count = 0;
    window.timer = setInterval(play, 10);
    return $('#start').html('ストップ').removeClass('btn-primary').addClass('btn-warning');
  } else {
    clearInterval(window.timer);
    window.timer = false;
    return $('#start').html('スタート').addClass('btn-primary').removeClass('btn-warning');
  }
};

play = function() {
  add(sim());
  if (window.count % window.OUTPUT_FREQUENCY === 0) {
    return output();
  }
};

sim = function() {
  var buses, i, index, ref;
  buses = [];
  for (index = i = 0, ref = window.BUS_COUNT; 0 <= ref ? i < ref : i > ref; index = 0 <= ref ? ++i : --i) {
    buses.push(Math.random());
  }
  buses.sort();
  return buses;
};

calcWait = function(me, buses) {
  var bus, i, len, res, wait;
  res = null;
  for (i = 0, len = buses.length; i < len; i++) {
    bus = buses[i];
    wait = bus - me;
    if (wait >= 0 && (res === null || wait < res)) {
      res = wait;
    }
  }
  if (res === null) {
    res = 1 - me;
  }
  return res;
};

add = function(buses) {
  var me, wait;
  me = window.isFirst ? 0 : Math.random();
  wait = calcWait(me, buses);
  window.average = (window.average * window.count + wait) / (window.count + 1);
  window.count++;
  if (window.bests.length < window.RANK_COUNT) {
    window.bests.push({
      me: me,
      wait: wait,
      buses: buses
    });
  } else if (window.bests[window.bests.length - 1]['wait'] > wait) {
    window.bests.push({
      me: me,
      wait: wait,
      buses: buses
    });
    window.bests.sort(function(a, b) {
      return a['wait'] - b['wait'];
    });
    window.bests.pop();
  }
  if (window.worsts.length < window.RANK_COUNT) {
    return window.worsts.push({
      me: me,
      wait: wait,
      buses: buses
    });
  } else if (window.worsts[window.worsts.length - 1]['wait'] < wait) {
    window.worsts.push({
      me: me,
      wait: wait,
      buses: buses
    });
    window.worsts.sort(function(a, b) {
      return b['wait'] - a['wait'];
    });
    return window.worsts.pop();
  }
};

output = function() {
  $('#average').html(timeFormat(window.average * window.TIME_MINUTES) + ' / ' + window.count + '回');
  $('tbody').html('');
  $('tbody').append($('<th>').attr('colspan', '2').html('最短'));
  addLines(window.bests, true);
  $('tbody').append($('<th>').attr('colspan', '2').html('最長'));
  return addLines(window.worsts);
};

addLines = function(results, secondFloat) {
  var borderDiv, bus, i, j, len, len1, ref, result, results1, td, tr;
  if (secondFloat == null) {
    secondFloat = false;
  }
  results1 = [];
  for (i = 0, len = results.length; i < len; i++) {
    result = results[i];
    tr = $('<tr>');
    td = $('<td>');
    borderDiv = $('<div>').addClass('graph').css('width', window.BORDER_WIDTH);
    ref = result['buses'];
    for (j = 0, len1 = ref.length; j < len1; j++) {
      bus = ref[j];
      $(borderDiv).append($('<span>').addClass('point').html('●').css('left', window.BORDER_WIDTH * bus));
    }
    $(borderDiv).append($('<span>').addClass('point me').html('●').css('left', window.BORDER_WIDTH * result['me']));
    td.append(borderDiv);
    tr.append(td);
    tr.append($('<td>').addClass('right').html(timeFormat(result['wait'] * window.TIME_MINUTES, secondFloat)));
    results1.push($('tbody').append(tr));
  }
  return results1;
};

timeFormat = function(minutes, secondFloat) {
  var minute, res, second;
  if (secondFloat == null) {
    secondFloat = false;
  }
  minute = Math.floor(minutes);
  second = secondFloat ? sprintf('%.4f', (minutes % 1) * 60) : Math.floor((minutes % 1) * 60);
  res = '';
  if (minute > 0) {
    res += minute + '分';
  }
  return res += second + '秒';
};
